export const SITE_CONFIG = {
  name: process.env.NEXT_PUBLIC_SITE_NAME || 'Gás Infinito',
  title: 'O Segredo do GÁS INFINITO no Tatame',
  description: 'Planilha de treino específica para jiu-jitsu - 17 semanas + bônus. Treine com eficiência e transforme seu gás no tatame!',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://gasinfinito.com',
  ogImage: '/images/faixa-preta-energia.png',
  links: {
    instagram: process.env.NEXT_PUBLIC_INSTAGRAM_URL || 'https://www.instagram.com/lucioflaviopersonalbjj/',
    hotmart: process.env.NEXT_PUBLIC_HOTMART_URL || 'https://pay.hotmart.com/U100991696O?off=npmpk04i',
    developer: process.env.NEXT_PUBLIC_DEVELOPER_URL || 'https://www.instagram.com/humbertodev.js/',
  },
  creator: 'Lúcio Flávio',
  publisher: 'Gás Infinito',
  keywords: [
    'jiu-jitsu',
    'treino',
    'gás infinito',
    'planilha',
    'peso corporal',
    'performance',
    'tatame',
    'lúcio flavio',
    'metodologia',
    'alto rendimento',
    'competição',
    'faixa preta',
    'campeão mundial',
  ],
  authors: [
    {
      name: 'Lúcio Flávio',
      role: 'Professor e Criador da Metodologia',
      achievements: [
        'Bi-Campeão Mundial IBJJF (2005 / 2019)',
        'Tri-Campeão Brasileiro CBJJ (2019 / 2021 / 2025)',
        'Tri-Campeão Internacional Master IBJJF (2016 / 2018 / 2019)',
        'Bi-Campeão Brasileiro por Equipes CBJJ (2018 / 2019)',
      ],
    },
  ],
  product: {
    name: process.env.NEXT_PUBLIC_PRODUCT_NAME || 'Gás Infinito - Planilha de Treino',
    price: parseFloat(process.env.NEXT_PUBLIC_PRODUCT_PRICE || '29.90'),
    originalPrice: parseFloat(process.env.NEXT_PUBLIC_PRODUCT_ORIGINAL_PRICE || '97.00'),
    currency: process.env.NEXT_PUBLIC_PRODUCT_CURRENCY || 'BRL',
    category: 'product',
    features: [
      'Planilha em PDF com circuitos prontos',
      'Exercícios com link direto para vídeos',
      'Organização para facilitar a execução',
      'Bônus: Treino completo de mobilidade',
    ],
  },
} as const;
